name: Transaction PR Checker

on:
  pull_request_target:
    branches: '**'
    types: [ opened, synchronize, reopened ]

jobs:

  build:

    name: Build
    needs: check-code-formatting
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21
          cache: 'maven'
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
        id: extract_branch

      - name: Start Kafka
        uses: 280780363/kafka-action@v1.0
        with:
          kafka version: "3.5.1" # Optional, kafka version
          zookeeper version: "latest" # Optional, zookeeper version
          kafka port: 9092 # Optional, kafka port
          zookeeper port: 2181 # Optional, zookeeper port
          auto create topic: "true" # Optional, auto create kafka topic
      
      - name: Build Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            if [ -n "${{ github.event.pull_request.number }}" ]; then
              MAVEN_OPTS="-Xmx4096m" mvn -B clean verify \
                org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
                -Dsonar.pullrequest.branch=${{ steps.extract_branch.outputs.branch }} \
                -Dsonar.pullrequest.base=master
            else
              echo "No Sonar PR analysis as this is not a Pull Request"
            fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/voltmasters/transaction:pr-snapshot
  
  
  check-code-formatting:

    name: Check Code Formatting

    strategy:
      matrix:
        platform: [ ubuntu-latest , macos-latest , windows-latest ]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 21
        cache: 'maven'
    
    - name: Check Code Formatting
      run: |
        mvn -e spotless:check
        echo "Run the command 'mvn spotless:apply' to fix Java formatting if this job fails or Build with Maven"
